# 권한
sudo: required
#사용 언어
language: node_js
#docker
services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t nnyong/tavis-docker-react-app -f Dokerfile.dev .
#run test -> test 끝나면 exit(-e)
  script:
  - docker run -e CI=true nnyong/tavis-docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"

##배포 관련
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "tavis-docker-react-app"
  env: "Tavisdockerreactapp-env-2"
  bucket_name: "elasticbeanstalk-ap-northeast-2-445811043890"
  bucket_path: "tavis-docker-react-app"
  on:
    branch: master