sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t nnyong/docker-react-app -f Dokerfile.dev .

  script:
  - docker run -e CI=true nnyong/docker-react-app npm run test --

after_success:
  - echo "Test success"
  